#!/usr/bin/env node

'use strict';

const fs = require('fs-extra');
const crypto = require('crypto');

function randomBase64String() {
    return crypto.randomBytes(64).toString('base64').slice(0, 64);
}

if (!fs.existsSync('.credentials')) {
    console.error('No .credentials folder!'
        + ' Make sure you\'re running this from the project root and have copied .credentials-template into .credentials.');
    process.exit(1);
} else if (fs.existsSync('.credentials/set-local-credentials.sh')) {
    console.log('File already exists .credentials/set-local-credentials.sh');
} else {
    const content = `
export FLEM_ENV="local-dev"

# Localhost
export DB_HOST="${process.env.DB_HOST}"
export DB_NAME="${process.env.DB_NAME}"
export DB_USER="${process.env.DB_USER}"
export DB_PASSWORD="${process.env.DB_PASSWORD}"

## AWS databases. Details are in Zoho. Connections allowed from Softwire offices only.
# LIVE
# export DB_HOST=""
# export DB_NAME="wordpress"
# export DB_USER=""
# export DB_PASSWORD=""
# export WP_CONTENT_URL="http://origin.flemingfund.org/wp-content/"

# STAGE
# export DB_HOST=""
# export DB_NAME="wordpress"
# export DB_USER=""
# export DB_PASSWORD=""
# export WP_CONTENT_URL="http://fleming-stage.eu-west-1.elasticbeanstalk.com/wp-content/"

# TEST
# export DB_HOST=""
# export DB_NAME="wordpress"
# export DB_USER=""
# export DB_PASSWORD=""
# export WP_CONTENT_URL="http://fleming-test.eu-west-1.elasticbeanstalk.com/wp-content/"


export AUTH_KEY="${randomBase64String()}"
export SECURE_AUTH_KEY="${randomBase64String()}"
export LOGGED_IN_KEY="${randomBase64String()}"
export NONCE_KEY="${randomBase64String()}"
export AUTH_SALT="${randomBase64String()}"
export SECURE_AUTH_SALT="${randomBase64String()}"
export LOGGED_IN_SALT="${randomBase64String()}"
export NONCE_SALT="${randomBase64String()}"
`;
    fs.writeFile('.credentials/set-local-credentials.sh', content, function (err) {
        if (err) throw err;
        console.log('Created file .credentials/set-local-credentials.sh');
    })
}
